dist: trusty
sudo: false
group: beta
language: ruby
cache: bundler
before_install:
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler -v 1.11.2
script: "TESTOPTS=-v bundle exec rake test"
branches:
  only: [master]
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.6.0
  - jruby-head
  - rbx-3
matrix:
  include:
    - rvm: 2.1
      gemfile: gemfiles/2.1-Gemfile
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3
    - rvm: ruby-head
