dist: trusty
sudo: false
group: beta
language: ruby
cache: bundler
before_install:
  # https://github.com/travis-ci/travis-ci/issues/9383#issuecomment-377680108
  # recent versions of RubyGems include bundler
  - gem update --system

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
  - jruby-9.2.0.0

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      env: RUBYOPT="--jit"
    - rvm: 2.3.8
      os: osx
    - rvm: 2.5.3
      os: osx
    - rvm: jruby-head
    - rvm: rbx-3
      
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head
      env: RUBYOPT="--jit"
    - rvm: jruby-head
    - rvm: rbx-3

env:
  global:
    - TESTOPTS="-v"
