name: Check Changelog

on:
 pull_request:
  types: [opened, reopened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !(   contains(github.event.pull_request.title, '[changelog skip]')
        || contains(github.event.pull_request.title, '[skip changelog]')
        || contains(github.event.pull_request.title, '[ci skip]')
        ||Â contains(github.event.pull_request.title, '[skip ci]'))

    steps:
    - uses: actions/checkout@v1
    - name: Check that CHANGELOG is touched
      run: |
        git diff remotes/origin/${{ github.base_ref }} --name-only | grep History.md
