name: MRI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}${{ matrix.no-ssl }}${{ matrix.yjit }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, macos-10.15, macos-11, windows-2022 ]
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', head ]
        no-ssl: ['']
        yjit: ['']
        include:
          - { os: windows-2022 , ruby: ucrt }
          - { os: windows-2022 , ruby: 2.7  , no-ssl: ' no SSL' }
          - { os: ubuntu-20.04 , ruby: head , yjit: ' yjit' }
          - { os: ubuntu-20.04 , ruby: 2.7  , no-ssl: ' no SSL' }

        exclude:
          - { os: ubuntu-20.04 , ruby: 2.2  }
          - { os: ubuntu-20.04 , ruby: 2.3  }
          - { os: windows-2022 , ruby: head }
          - { os: macos-10.15  , ruby: 2.6  }
          - { os: macos-10.15  , ruby: 2.7  }
          - { os: macos-10.15  , ruby: '3.0' }
          - { os: macos-11     , ruby: 2.2  }
          - { os: macos-11     , ruby: 2.3  }

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby
        uses: MSP-Greg/setup-ruby-pkgs@win-ucrt-2
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: ragel
          brew: ragel
          mingw: openssl ragel
          bundler-cache: true
          setup-ruby-ref: MSP-Greg/ruby-setup-ruby/win-ucrt-1
        timeout-minutes: 10

      # Windows error thrown, doesn't affect CI
      - name: update rubygems for Ruby 2.2
        if: matrix.ruby < '2.3'
        run: gem update --system 2.7.11 --no-document
        continue-on-error: true
        timeout-minutes: 5

      # Fix RubyGems warnings about required_ruby_version bug with Bundler
      - name: update rubygems for Ruby 2.2
        if: matrix.ruby >= '2.3' && matrix.ruby < '2.6'
        run: gem update --system 3.2.3 --no-document
        continue-on-error: true
        timeout-minutes: 5

      - name: Compile Puma without SSL support
        if: matrix.no-ssl == ' no SSL'
        shell: bash
        run: echo 'DISABLE_SSL=true' >> $GITHUB_ENV

      - name: set WERRORFLAG
        shell: bash
        run: echo 'MAKE_WARNINGS_INTO_ERRORS=true' >> $GITHUB_ENV

      - name: compile
        run:  bundle exec rake compile

      - name: rubocop
        run: bundle exec rake rubocop

      - name: Use yjit
        if: matrix.yjit == ' yjit'
        shell: bash
        run: echo 'RUBYOPT=--yjit' >> $GITHUB_ENV

      - name: test
        timeout-minutes: 10
        run: bundle exec rake test:all
