name: Puma

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.os }}, ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, macos ]
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, ruby-head, jruby ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, ragel
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: ragel
          brew: ragel

      - name: bundle install
        run:  |
          # update RubyGems in Ruby 2.2, bundle install
          if [[ "${{ matrix.ruby }}" < "2.3" ]]; then
            gem update --system 2.7.10 --no-document
          fi
          bundle install --jobs 4 --retry 3 --path=.bundle/puma

      - name: compile
        run:  bundle exec rake compile

      - name: test
        timeout-minutes: 10
        run:  |
          # RubyGems < 3, no frozen strings
          if [[ "2.6" < "${{ matrix.ruby }}.0" ]]; then
            export RUBYOPT="--enable=frozen-string-literal"
          fi
          bundle exec rake

  win32:
    name: >-
      ${{ matrix.os }}, ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ 2.3, 2.4, 2.5, 2.6, 2.7, mingw ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, ragel, openssl
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          mingw: _upgrade_ openssl ragel

      - name: bundle install
        run:  bundle install --jobs 4 --retry 3 --path=.bundle/puma

      - name: compile
        run:  |
          # Windows Ruby < 2.4 do not use MSYS2 OpenSSL
          if ('${{ matrix.ruby }}' -lt '2.4') {
            bundle exec rake compile -- --with-openssl-dir=C:/openssl-win
          } else {
            bundle exec rake compile
          }

      - name: test
        timeout-minutes: 10
        run:  |
          # RubyGems < 3, no frozen strings
          if ('${{ matrix.ruby }}' -ge '2.6') {
            $env:RUBYOPT = '--enable=frozen-string-literal'
          }
          bundle exec rake
