name: Puma

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.os }}, ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(contains(github.event.pull_request.title, '[ci skip]')
        || contains(github.event.head_commit.message, '[ci skip]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, macos ]
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, head, jruby, truffleruby-head ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, ragel
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: ragel
          brew: ragel

      - name: bundle install
        run:  |
          # update RubyGems in Ruby 2.2, bundle install
          if [[ "${{ matrix.ruby }}" < "2.3" ]]; then
            gem update --system 2.7.10 --no-document
          fi
          bundle install --jobs 4 --retry 3 --path=.bundle/puma

      - name: compile
        run:  bundle exec rake compile

      - name: test
        timeout-minutes: 8
        run: bundle exec rake

  win32:
    name: >-
      ${{ matrix.os }}, ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(contains(github.event.pull_request.title, '[ci skip]')
        || contains(github.event.head_commit.message, '[ci skip]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, mingw ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, ragel, openssl
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          mingw: _upgrade_ openssl ragel

      - name: bundle install
        run:  |
          # update RubyGems in Ruby 2.2, bundle install
          if ('${{ matrix.ruby }}' -lt '2.3') {
            gem update --system 2.7.10 --no-document
          }
          bundle install --jobs 4 --retry 3 --path=.bundle/puma

      - name: compile
        run:  |
          bundle exec rake compile

      - name: test
        timeout-minutes: 8
        run: bundle exec rake

  allowedFailures:
    name: >-
      ${{ matrix.cfg.os }}, ${{ matrix.cfg.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.cfg.os }}
    if: |
      !(contains(github.event.pull_request.title, '[ci skip]')
        || contains(github.event.head_commit.message, '[ci skip]'))
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, ruby: jruby-head }

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, ragel
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.cfg.ruby }}
          apt-get: ragel
          brew: ragel

      - name: bundle install
        run:  |
          bundle install --jobs 4 --retry 3 --path=.bundle/puma

      - name: compile
        continue-on-error: true
        run:  bundle exec rake compile

      - name: test
        timeout-minutes: 8
        continue-on-error: true
        if: success()
        run: bundle exec rake
